try {
    throw "error";
} finally { // error: Uncaught exception: "error"
    print("finally"); // expect: finally
}