try {
    throw "error";
} catch(err) {
    print(err); // expect: error
}